services:
  - type: web
    name: weather-ai-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
